INSERT INTO
    tidbits.codemymobile_users (id, "name", email, avatar)
values
    (
        1,
        'ravi',
        'ravikantsharma2169@gmail.com',
        'https://avatars0.githubusercontent.com/u/24990000?s=400&u=dbce2090b78b7108c7cbad0d1bf8fa2c8044c9d8&v=4'
    ),
    (
        2,
        'surya',
        'surya@gmail.com',
        'https://avatars0.githubusercontent.com/u/24990000?s=400&u=dbce2090b78b7108c7cbad0d1bf8fa2c8044c9d8&v=4'
    ),
    (
        3,
        'rekha',
        'rekha@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFWBnyvJtrWYVL5q2Nwl1UkCOxOPxFGoORjg&usqp=CAU'
    ),
    (
        4,
        'anusha',
        'anusha@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLaoiVChJYmLSdfsWtgKL_deeSguvjFYeHqw&usqp=CAU'
    ),
    (
        5,
        'shreya',
        'shreya@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQOALqcMjby_cOSIr-3GFWRO_zY_j0qcB4zRA&usqp=CAU'
    ),
    (
        6,
        'himanshi',
        'himanshi@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTwzP4P5SyVXAZL7qK-pIIFD5jzU2gm0kELXQ&usqp=CAU'
    ),
    (
        7,
        'megha',
        'megha@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFWBnyvJtrWYVL5q2Nwl1UkCOxOPxFGoORjg&usqp=CAU'
    ),
    (
        8,
        'hemant',
        'hemant@gmail.com',
        'https://avatars0.githubusercontent.com/u/24990000?s=400&u=dbce2090b78b7108c7cbad0d1bf8fa2c8044c9d8&v=4'
    ),
    (
        9,
        'ashish',
        'ashish@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFWBnyvJtrWYVL5q2Nwl1UkCOxOPxFGoORjg&usqp=CAU'
    ),
    (
        10,
        'gagan',
        'gagan@gmail.com',
        'https://avatars0.githubusercontent.com/u/24990000?s=400&u=dbce2090b78b7108c7cbad0d1bf8fa2c8044c9d8&v=4'
    ),
    (
        11,
        'shruti',
        'shruti@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLaoiVChJYmLSdfsWtgKL_deeSguvjFYeHqw&usqp=CAU'
    ),
    (
        12,
        'pallavi',
        'pallavi@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFWBnyvJtrWYVL5q2Nwl1UkCOxOPxFGoORjg&usqp=CAU'
    ),
    (
        13,
        'bijay',
        'bijay@gmail.com',
        'https://avatars0.githubusercontent.com/u/24990000?s=400&u=dbce2090b78b7108c7cbad0d1bf8fa2c8044c9d8&v=4'
    ),
    (
        14,
        'ankur',
        'ankur@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLaoiVChJYmLSdfsWtgKL_deeSguvjFYeHqw&usqp=CAU'
    ),
    (
        15,
        'deepak',
        'deepak@gmail.com',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTwzP4P5SyVXAZL7qK-pIIFD5jzU2gm0kELXQ&usqp=CAU'
    );